"""Shared visual system for reports that must match the fixed TMA39 presentation."""

REPORT_TEMPLATE_ID = "tma39-sam3-presentation-v1"

STYLE = r"""
:root{--ink:#182329;--muted:#52636b;--line:#d4dde1;--soft:#f4f7f8;--teal:#087f83;--blue:#126b9e;--green:#127854;--red:#a13e3e;--gold:#a66f00}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;color:var(--ink);font-family:Arial,Helvetica,sans-serif;letter-spacing:0;line-height:1.45;background:#fff}
header,section{padding:38px max(28px,calc((100vw - 1320px)/2));border-bottom:1px solid var(--line)}header{background:#182329;color:#fff;padding-top:46px;padding-bottom:42px}
h1{font-size:40px;line-height:1.08;margin:0 0 12px}h2{font-size:28px;margin:0 0 12px}h3{font-size:19px;margin:0 0 8px}h4{font-size:16px;margin:0 0 6px}p{margin:7px 0 13px}.lede{font-size:20px;max-width:1080px;color:#d9e5e8}.eyebrow{font-size:13px;text-transform:uppercase;font-weight:700;color:#9ed9d7;margin-bottom:8px}
.top-nav{display:flex;flex-wrap:wrap;gap:9px;margin-top:18px}.top-nav a{padding:9px 12px;border:1px solid #82b8b9;color:#fff;text-decoration:none;font-weight:700;background:#25343a;border-radius:4px}
.metrics{display:grid;grid-template-columns:repeat(6,minmax(120px,1fr));gap:10px;margin:18px 0}.metric{border:1px solid var(--line);padding:12px;background:#fff;min-height:84px;border-radius:5px}.metric b{display:block;font-size:27px;line-height:1.05}.metric span{display:block;color:var(--muted);font-size:13px;margin-top:6px}header .metric{background:#25343a;border-color:#44565e}header .metric span{color:#d1dfe3}
.note{padding:13px 15px;border-left:5px solid var(--teal);background:#edf6f6;margin:16px 0}.warning{border-left-color:var(--gold);background:#fff7e3}.result-note{border-left-color:var(--green);background:#edf7f2}
.flow{display:grid;grid-template-columns:repeat(7,minmax(0,1fr));margin:18px 0}.flow.next-flow{grid-template-columns:repeat(5,minmax(0,1fr))}.flow div{padding:12px;border-top:4px solid var(--teal);border-right:1px solid var(--line);background:var(--soft);min-height:130px}.flow div:last-child{border-right:0}.flow .planned{border-top-color:var(--gold);background:#fff9ea}.flow b{display:block;margin-bottom:6px}.stage{display:block;margin-top:8px;font-size:11px;font-weight:700;text-transform:uppercase;color:var(--muted)}
.grid2,.grid3,.grid4{display:grid;gap:16px;align-items:start}.grid2>* ,.grid3>* ,.grid4>*{min-width:0}.grid2{grid-template-columns:repeat(2,minmax(0,1fr))}.grid3{grid-template-columns:repeat(3,minmax(0,1fr))}.grid4{grid-template-columns:repeat(4,minmax(0,1fr))}
figure{margin:0;border:1px solid var(--line);background:#fff;min-width:0}figure h3{padding:12px 14px 0}figure img{display:block;width:100%;height:auto}figcaption{padding:9px 14px 13px;color:var(--muted);font-size:13px}.matched figure img{aspect-ratio:1/1;object-fit:contain;background:#fff}
.count-flow{font-size:22px;font-weight:700;padding:17px;border:1px solid var(--line);background:var(--soft);text-align:center;margin:17px 0}
.table-wrap{overflow-x:auto;max-width:100%;border:1px solid var(--line);margin:12px 0 18px}table{width:100%;border-collapse:collapse;min-width:760px}th,td{padding:10px 11px;border-bottom:1px solid var(--line);text-align:left;vertical-align:top;font-size:14px}th{background:#eaf0f2;font-size:13px}tbody tr:last-child td{border-bottom:0}
.legend{display:flex;flex-wrap:wrap;gap:10px 18px;padding:12px 14px;border:1px solid var(--line);background:var(--soft);margin:11px 0 18px}.legend span{display:inline-flex;gap:7px;align-items:center;font-size:13px;font-weight:700}.legend i{display:block;width:17px;height:17px;border:1px solid #66777f}
.method-strip{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin:17px 0}.method-strip div{border-top:4px solid var(--teal);padding:11px;background:var(--soft);min-height:96px}.method-strip b{display:block;margin-bottom:5px}
.factor-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.factor{display:grid;grid-template-columns:34px minmax(0,1fr);gap:9px;padding:9px;border:1px solid var(--line);background:#fff}.factor i{display:block;width:34px;height:34px;border:1px solid #405159}.factor b,.factor small{display:block}.factor small{color:var(--muted);margin-top:2px}
.explorer-controls{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;padding:14px;border:1px solid var(--line);background:var(--soft)}label{display:block;font-size:13px;font-weight:700;margin-bottom:5px}select{width:100%;padding:9px;border:1px solid #aebbc1;background:#fff;font:inherit}
.candidate-tabs{display:flex;flex-wrap:wrap;gap:7px;padding:12px 0 14px}.candidate-tabs button{border:1px solid #aab8be;background:#fff;padding:8px 10px;font:inherit;font-size:13px;font-weight:700;cursor:pointer;border-radius:4px}.candidate-tabs button.active{background:#e3f1f2;border-color:var(--teal);color:#0b5d61}
.result-head{display:flex;flex-wrap:wrap;gap:8px;margin:5px 0 12px}.chip{display:inline-block;padding:6px 9px;border:1px solid var(--line);background:var(--soft);font-size:13px;font-weight:700}.chip.correct{background:#e9f6ef;border-color:#9fceb7;color:#0b6b43}.chip.incorrect{background:#fff0ef;border-color:#dfb0ac;color:#8c2e2e}
.relation-metrics{display:grid;grid-template-columns:repeat(6,minmax(100px,1fr));gap:9px;margin:12px 0}.relation-metrics div{padding:10px;border:1px solid var(--line);background:#fff}.relation-metrics b{display:block;font-size:20px}.relation-metrics span{font-size:12px;color:var(--muted)}
.result-images{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.result-images figure img{aspect-ratio:1/1;object-fit:contain;background:#fff}.overlay-key{display:flex;flex-wrap:wrap;gap:12px;margin:8px 0}.overlay-key span{font-size:13px;font-weight:700}.overlay-key i{display:inline-block;width:15px;height:15px;margin-right:5px;vertical-align:-2px}
.scores{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:6px 18px;margin-top:10px}.score{display:grid;grid-template-columns:145px minmax(80px,1fr) 34px;gap:7px;align-items:center;font-size:13px}.bar{height:12px;background:#e2e9ec}.bar i{display:block;height:100%;background:var(--blue)}
.subtle{color:var(--muted);font-size:13px}.section-intro{max-width:1050px}.full-width-image img{max-height:none;object-fit:contain}.footer{font-size:13px;color:var(--muted)}
@media(max-width:1050px){.metrics{grid-template-columns:repeat(3,1fr)}.flow{grid-template-columns:repeat(2,1fr)}.grid3,.grid4,.factor-grid{grid-template-columns:repeat(2,1fr)}.relation-metrics{grid-template-columns:repeat(3,1fr)}}
@media(max-width:700px){header,section{padding:26px 15px}h1{font-size:31px}.metrics,.grid2,.grid3,.grid4,.factor-grid,.explorer-controls,.result-images,.scores,.method-strip{grid-template-columns:1fr}.relation-metrics{grid-template-columns:repeat(2,1fr)}.flow{grid-template-columns:1fr}.flow div{border-right:0}.top-nav a{width:100%}}
"""
